### ISSUE TITLE
Python2 related errors

### ISSUE THREAD

**Issue by Thrathra** [ros-melodic-arch/ros-melodic-rosserial-python#1]
It seems this package retrieves an old version of rosserial-python which still uses python2.
It throws errors mainly related to python2 -> python3 issues.
The melodic-devel branch seems to be working.

**Comment by acxz** [comment]
Can you post the specific errors?

**Comment by Thrathra** [comment]
After a few tests, the melodic-devel needs patches too (classic python2 print for example).
The fix below are needed for the actual arch package.
Here is the first error using "rosrun rosserial_python serial_node.py":
`Traceback (most recent call last):`
`File "/opt/ros/melodic/lib/rosserial_python/serial_node.py", line 39, in <module>`
`from rosserial_python import SerialClient, RosSerialServer`
`File "/opt/ros/melodic/lib/python3.8/site-packages/rosserial_python/__init__.py", line 1, in <module>`
`from SerialClient import *`
`ModuleNotFoundError: No module named 'SerialClient'`

I modified SerialClient to rosserial_python.SerialClient in __init__.py

In SerialClient.py there are:
- two old styled prints (lines 224 and 237)
- an old style except (line 314) 
- a wrong module import (line 42) : import StringIO -> from io import StringIO
- a wrong module import (line 48) : from Queue import Queue -> from queue import Queue

Going through the needed modifications I end with a yaml related warning:
`/opt/ros/melodic/lib/python3.8/site-packages/rospy/client.py:104: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  mappings[src[1:]] = yaml.load(dst)`

I hope it helps.

**Comment by Thrathra** [comment]
I got another error running the node:
`Exception in thread Thread-6:`
`Traceback (most recent call last):`
`File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner`
`self.run()`
`File "/usr/lib/python3.8/threading.py", line 870, in run`
`self._target(*self._args, **self._kwargs)`
`File "/opt/ros/melodic/lib/python3.8/site-packages/rosserial_python/SerialClient.py", line 784, in processWriteQueue`
`elif isinstance(data, basestring):`
`NameError: name 'basestring' is not defined`

**Comment by acxz** [comment]
I am afraid this is beyond the packaging tasks that we deal with. The best place to file these issues would be upstream, as they can easily get the fixes to these issues merged. If you do create a patch for this fix, we will readily add it.

**Comment by Thrathra** [comment]
Oh okay, thanks for the info, I'll look into it.

**Comment by acxz** [comment]
We will still keep this issue open since you are dealing with this problem. Until upstream releases a new version with this fix or if we patch it.

**Comment by acxz** [comment]
upstream issue: https://github.com/ros-drivers/rosserial/issues/471
